name: CI - Train ML Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Run training script
    - name: Run training script with MLflow logging
      env:
        DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_REPO: ${{ secrets.DAGSHUB_REPO }}
      run: |
        python train_with_mlflow.py

    # 5. Upload model artifacts to GitHub
    - name: Upload trained model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
